### ISSUE TITLE
update_to_actual_grb: using 0m as relevant distances results in actualisations of >0m

### ISSUE THREAD

**Issue by dieuska** [OnroerendErfgoed/brdr#121]
when setting the autoupdateborders (brdrQ) to 0m update-range; the script still gives results for relevant distance >0m. to check what happend in Autoupdatborders or 'update-to_actual_grb' (see case puursSintamands)

**Comment by dieuska** [comment]
This is fixed in brdrQ-autoupdateborders that the correct MAX_REL_DIST is used inside update_to_actual_grb. But gives an error in brdr -update_toActual_grb(). 
Probably the reason is that the predictor gives an empty list of predictions, and no record is found to check (Index out of range, see below)
------------

Traceback (most recent call last):
File "C:\Users/KarelDieussaert/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\brdrq\brdrq_algorithm_autoupdateborders.py", line 349, in processAlgorithm
fcs_actualisation = update_to_actual_grb(fc, id_theme_fieldname=self.ID_THEME_FIELDNAME,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\KarelDieussaert\AppData\Roaming\Python\Python312\site-packages\brdr\grb.py", line 438, in update_to_actual_grb
dict_evaluated, prop_dictionary = actual_aligner.evaluate(
^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\KarelDieussaert\AppData\Roaming\Python\Python312\site-packages\brdr\aligner.py", line 644, in evaluate
dict_series, dict_affected_predictions, diffs = self.predictor(
^^^^^^^^^^^^^^^
File "C:\Users\KarelDieussaert\AppData\Roaming\Python\Python312\site-packages\brdr\aligner.py", line 593, in predictor
][relevant_distances[0]]
~~~~~~~~~~~~~~~~~~^^^
IndexError: index 0 is out of bounds for axis 0 with size 0

Execution failed after 9.33 seconds

**Comment by dieuska** [comment]
fixed
