### ISSUE TITLE
adding a safe_equals-function to catch GEOsException

### ISSUE THREAD

**Issue by dieuska** [OnroerendErfgoed/brdr#71]
shapely.equals can fail on GEOSException (see case:  https://github.com/OnroerendErfgoed/brdrQ/issues/44 where this happens).

By making a safe_equals version (like for safe_difference etc.) this can be catched.

**Comment by dieuska** [comment]
START
Resultaten: {'OUTPUT': 'Berekend_62af99e7_7aa0_46d4_9d48_2fd9c69dc0c3'}
Resultaten: {'OUTPUT': 'Gerepareerde_geometrie_n_b81a4d47_9cf9_4d67_98a4_c043bd146a74'}
Resultaten: {'OUTPUT': 'Geom_info_toegevoegd_577d8bf9_91a5_4593_9423_a86f5a7554d7'}
Resultaten: {'OUTPUT': 'Verwijderde_Z_M_08f87445_d57b_4aa5_9d1b_c0f14aafcabf'}
Resultaten: {'OUTPUT': 'Gebufferd_ce5ac5b5_7883_4dd8_ac46_4dd7baf62a2f'}
Area of thematic zone: 9173165.924486674
1) BEREKENING - Thematic layer fixed
Er bestaat geen ruimtelijke index voor de invoerlaag, uitvoering zal ernstig zijn vertraagd
Resultaten: {'OUTPUT': 'Uitgenomen__locatie__5e31c8df_e1e0_414c_bf30_ba32c001bed5'}
Resultaten: {'OUTPUT': 'Berekend_4fbc1e02_e998_4c1b_ba47_f00fcdf68d12'}
Resultaten: {'OUTPUT': 'Gerepareerde_geometrie_n_df18525d_4f1c_447b_99d3_38b7e5c5d139'}
Resultaten: {'OUTPUT': 'Verwijderde_Z_M_8c60d22f_0d53_4f7e_ba07_c973b72f4aa7'}
2) BEREKENING - Reference layer fixed
Load thematic data
Load reference data
START PROCESSING
calculation for relevant distance (m): 7.0 - Predictions: True
Traceback (most recent call last):
File "C:\Users\saravdv\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts\autocorrectborders.py", line 748, in processAlgorithm
fcs = aligner.get_predictions_as_geojson(formula=self.FORMULA)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\saravdv\AppData\Roaming\Python\Python312\site-packages\brdr\aligner.py", line 610, in get_predictions_as_geojson
Optional: The descriptive formula is added as an attribute to the result"""
^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\saravdv\AppData\Roaming\Python\Python312\site-packages\brdr\aligner.py", line 529, in get_formula
equal = equals(geom_intersection, geom_reference)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\PROGRA~1\QGIS33~1.10\apps\Python312\Lib\site-packages\shapely\decorators.py", line 77, in wrapped
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "C:\PROGRA~1\QGIS33~1.10\apps\Python312\Lib\site-packages\shapely\predicates.py", line 744, in equals
return lib.equals(a, b, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
shapely.errors.GEOSException: TopologyException: side location conflict at 140385.83386061 193904.10317662999. This can occur if the input geometry is invalid.

Execution failed after 3662.55 seconden (1 uur 1 minuut 3 seconden)

Resultaatlagen laden
Algoritme 'brdrQ - AutoCorrectBorders' voltooid
